### ISSUE TITLE
 reporte de conexion

### ISSUE THREAD

**Issue by pichicho37** [HeberonYT/SkyFactory3#1]
como están ,estuve instalando los mods de SkyFactory3 pero cuando esta todo, entro a multijugador y no me carga el servidor y esta tachado con una x,probé con direcciones de otros servidores de igual modo, lo  y lo desinstale y  probé con minecraft original y allí si carga los servidores ,cual sera el problema que sucede solo cuando instalo SkyFactory3. Me olvido me muestra este mensaje java.net.connectexception connection refused no further information. En espera de su pronta respuesta  gracias.

**Comment by HeberonYT** [comment]
Hola amigo!
El problema fue que el servidor estuvo en mantenimiento desde las 7pm hasta la 1am. 
Durante ese periodo estuvo cerrado.
Pero verifica ahora y comenta si ya te aparece en la lista de Multijugador.
Saludos!
