### ISSUE TITLE
No puedo entrar :'v

### ISSUE THREAD

**Issue by Alexcynoer** [HeberonYT/SkyFactory3#15]
Me dice que hay un erro

**Comment by Alexcynoer** [comment]
![image](https://user-images.githubusercontent.com/24683632/34064365-00e760d8-e1be-11e7-968a-5ced4c7a7d12.png)

**Comment by Alexcynoer** [comment]
![image](https://user-images.githubusercontent.com/24683632/34064365-00e760d8-e1be-11e7-968a-5ced4c7a7d12.png)
eso es lo que me sale :'v

**Comment by HeberonYT** [comment]
Prueba con el lanzador viejo, puedes descargarlo aquí
http://heberon.com/descargas/Premium.exe
