### ISSUE TITLE
Me da error al entrar

### ISSUE THREAD

**Issue by RomaxX33PvP** [HeberonYT/SkyFactory3#18]
Caí al vacío y me sacó del server, intenté entrar y me dice que flying is not enabled in this server.

**Comment by HeberonYT** [comment]
Hola!
Entra en la siguiente página y en la pestaña Herramientas hay una opción que permite mover tu personaje al spawn principal.
Solo introduce tu Nick y sigue los pasos como si hicieras una compra.

Saludos!

http://skyfactory3.buycraft.net/category/1054726

**Comment by HeberonYT** [comment]
Hola!
Entra en la siguiente página
http://skyfactory3.buycraft.net/category/1054726

Allí introduce tu nick de Minecraft y selecciona la opción "Mover al Spawn"
Eso permitirá colocarte en el punto spawn del servidor y te sacará del lugar donde moriste.

Saludos!
