### ISSUE TITLE
¿El que no se genere la tumba al morir en la isla de otro es un bug?

### ISSUE THREAD

**Issue by RomaxX33PvP** [HeberonYT/SkyFactory3#19]
No lo se pero iba con mis cosas el jetpack se me quedo sin energía y la tumba no ha aparecido.¿Eso es un bug?

**Comment by HeberonYT** [comment]
Hola!
No precisamente, ya que el dueño de la isla donde moriste pudo cambiar las banderas de protección y evitar que se generaran tumbas de otros usuarios. 

Si te quedaste sin energía al volar, es mejor introducir el comando "/spawn" o hacerte TP al punto home de tu isla, incluso morir por caída al vacío pondrá tu tumba en la capa 1.

Saludos!
