### ISSUE TITLE
problema al entrar

### ISSUE THREAD

**Issue by EnderHerobrina12** [HeberonYT/SkyFactory3#2]
hola heberon después de que renunciaras el server para que fuera mejor me quede en mi isla con una amiga y ahora al entrar a las dos nos sale un error
Internal Exception: java.lang.IllegalArgumentException:The name extrautils2:chunkloader he's been registered twice, for Block(null) and Block(extrautils2:chunkloader).

**Comment by HeberonYT** [comment]
Pásame tu Nick y el de tu amiga por favor.

**Comment by EnderHerobrina12** [comment]
EnderHeroGirl12 y Melo_Cotona_YT

**Comment by EnderHerobrina12** [comment]
volvi a entrar y se me soluciono no se si a mi amiga tambien

**Comment by HeberonYT** [comment]
ok, si el problema persiste favor de escribirlo aquí mismo para abrir el ticket nuevamente.
