### ISSUE TITLE
Me dice eso al tratar de entrar al server

### ISSUE THREAD

**Issue by TheBlackWolf25** [HeberonYT/SkyFactory3#22]
![foto](https://user-images.githubusercontent.com/37153914/37247654-4096704e-249d-11e8-974e-cd13734a21b7.JPG)

**Comment by HeberonYT** [comment]
Parece que este problema no esta relacionado con el servidor, quizás la causa sea mojang, creo que estuvo offline durante un tiempo, por eso no puedes conectarte a ningún servidor.
Si aún tienes este problema, continua aportando detalles en esta conversación.
