### ISSUE TITLE
rango

### ISSUE THREAD

**Issue by grim3210** [HeberonYT/SkyFactory3#23]
hola yo he comprado mi rango en el server de apocalipsis minecraft... en que server me devolveran el rango ?

**Comment by HeberonYT** [comment]
hola!
Los rangos de Apocalipsis Minecraft 5 no se pasaron a ningún otro servidor, estuvieron disponibles durante todo el tiempo que el servidor funcionó pero terminaron al finalizar.
Actualmente los rangos en SkyFactory 3, BEYOND y LESDM Reloaded son permanentes, es decir que nunca se terminarán o vencerán.
Saludos!
