### ISSUE TITLE
Problema con el dragon

### ISSUE THREAD

**Issue by alefansole** [HeberonYT/SkyFactory3#3]
hola,hoy a las 5 de la mañana mate al drgon, el problema es que no dio nada, si si espere a que sea adulto, pero no dropeo ni xp ni el corazon...nada

**Comment by HeberonYT** [comment]
Hola!
Se están haciendo preparativos para programar automáticamente el spawneo del dragón, más información estará disponible pronto.

**Comment by HeberonYT** [comment]
Esto ya se ha implementado.
