### ISSUE TITLE
Bug Beneath

### ISSUE THREAD

**Issue by Yuch135** [HeberonYT/SkyFactory3#5]
Hola, resulta que puse el portal al beneath en la isla que compartimos mis amigos y yo. Le di click, y me llevó al beneath. Hasta ahí medio bien. Pero en cuanto me carga la dimensión, aparezco muerto, no hay ninguna pared ni nada que me sofoque, salgo en una cueva. Y resulta que aparezco en coordenadas fuera de el límite de la dimensión de beneath.

**Comment by HeberonYT** [comment]
Hola!, esto es debido al funcionamiento del mod, ejemplo; si tu isla esta en las coordenadas 100, 200, y allí colocas tu portal al Beneath, entonces aparecerás en las mismas coordenadas de esa dimensión.
El problema es que el mundo de las islas no tiene limite o borde, y cada que alguien crea una isla nueva se esta alejando del centro del spawn principal.
Por lo tanto si tu isla esta muy lejos del spawn principal en el overworld, aparecerás fuera del borde que esta establecido en el Beneath, actualmente 8Mil bloques de diámetro, y por ello te mata al entrar.
Te recomiendo colocar tu portal al Beneath en el spawn principal escondido de otros usuarios, así aparecerás en zona segura y podrás colocar un sethome en esa dimensión y volver a quitar el portal que pusiste en el spawn, así podrás ir a esa dimensión con tu punto home.
Ten cuidado al colocar tu portal en el spawn, ya que cualquier otro usuario podría usarlo o romperlo y llevárselo.
Por favor menciona tu nick para retirar tu tumba y devolverte las cosas.
